function [ AdvancedParam ] = MCsquare_advanced_GUI(handles, varargin)

HEIGHT = 660;
WIDTH = 700;

% create list of CT images loaded in OpenReggui
CT_Id_list = [];
Contour_Id_list = [];
for i=1:numel(handles.images.name)
    Modality = '';
    
    try
        Modality = handles.images.info{i}.OriginalHeader.Modality;
        if(isfield(handles.images.info{i}, 'Color'))
            Modality = 'RS';
        end
    catch
        continue
    end
    
    switch Modality
        case 'CT'
            CT_Id_list(end+1) = i;
        case 'RS'
            Contour_Id_list(end+1) = i;
        case 'OT'
            CT_Id_list(end+1) = i;   % To accept images generated in Matlab referred as "Other Modality"
    end
end

if(numel(CT_Id_list) > 0)
    CTString = handles.images.name(CT_Id_list);
else
    CTString = {'CT image not found !!'};
end


ROIdata = {};


% initialize advanced simulation parameters
if(nargin > 1 && isfield(varargin{1}, 'Simu4D'))
    AdvancedParam = varargin{1};
    
    if(numel(Contour_Id_list) > 0)
        for i=1:numel(Contour_Id_list)
            TV = check_contour_list(handles.images.name{Contour_Id_list(i)}, AdvancedParam.TV);
            OAR = check_contour_list(handles.images.name{Contour_Id_list(i)}, AdvancedParam.OAR);
            ROIdata = [ROIdata ; {logical(TV), logical(OAR), handles.images.name{Contour_Id_list(i)}}];
        end
    else
        ROIdata = {false, false, 'No contour found'};
    end
else
    AdvancedParam.Simu4D = 0;
    AdvancedParam.DoseAccumulation = 1;
    AdvancedParam.CT_phases = CTString{1};
    AdvancedParam.CT_list = 1;
    AdvancedParam.reference = CTString{1};
    AdvancedParam.Ref_list = 1;
    AdvancedParam.register = 1;
    AdvancedParam.CT_button = 'All img';
    
    AdvancedParam.Robustness = 0;
    AdvancedParam.ScenarioSampling = 0;
    AdvancedParam.NumScenarios = 0;
    AdvancedParam.setup_systematic = [5.0 5.0 5.0];
    AdvancedParam.setup_random = [1.0 1.0 1.0];
    AdvancedParam.range_systematic = 3.0;
    AdvancedParam.TV = {};
    AdvancedParam.OAR = {};
    
    if(numel(Contour_Id_list) > 0)
        for i=1:numel(Contour_Id_list)
            TV = check_contour_list(handles.images.name{Contour_Id_list(i)}, {'ctv','itv'});
            OAR = check_contour_list(handles.images.name{Contour_Id_list(i)}, {'lung','heart', 'spinal', 'cord'});
            ROIdata = [ROIdata ; {logical(TV), logical(OAR), handles.images.name{Contour_Id_list(i)}}];
        end
    else
        ROIdata = {false, false, 'No contour found'};
    end
    
end




%% create GUI

% Create a window for the GUI
window = figure('Name', '4D simulation parameters', ...
    'Units', 'Pixels', ...
    'Color', [0.8 0.8 0.8], ...
    'Position', [200 200 WIDTH*1.2 HEIGHT]);

LeftPosition = HEIGHT - 40;
LeftPadding = WIDTH*0.05;
RightPosition = LeftPosition;
RightPadding = WIDTH*0.65;

%%%%%%%%%%% Left pannel %%%%%%%%%%%%

% 4D mode
Simu4D_label = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', '4D simulation mode', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'FontWeight', 'Bold', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'left', ...
    'Position', [LeftPadding LeftPosition WIDTH/2 30]);

LeftPosition = LeftPosition - 40;

%enable 4D mode
Enable_4D =  uicontrol( 'Parent', window, ...
    'Style', 'checkbox', ...
    'String', 'Enable 4D simulation mode', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'HorizontalAlignment', 'left', ...
    'Callback', @Enable_4D_Callback, ...
    'Position', [LeftPadding LeftPosition WIDTH/2 22]);

LeftPosition = LeftPosition - 40;

% 4DCT phases
CT_label = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'Select all 4DCT phases', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'FontWeight', 'Bold', ...
    'HorizontalAlignment', 'left', ...
    'Position', [LeftPadding LeftPosition WIDTH/2 20]);

LeftPosition = LeftPosition - 150;

CT_list = uicontrol(   'Parent', window, ...
    'Style', 'listbox', ...
    'String', CTString, ...
    'Enable', 'off', ...
    'max', 10, ...
    'Callback', @CT_change_Callback, ...
    'Position', [LeftPadding LeftPosition WIDTH/2 150]);

CT_button = uicontrol(   'Parent', window, ...
    'Style', 'pushbutton', ...
    'String', 'All img', ...
    'Enable', 'off', ...
    'HorizontalAlignment', 'left', ...
    'Position', [(LeftPadding+WIDTH/2-65) LeftPosition 50 20], ...
    'Callback', @CT_button_Callback);

LeftPosition = LeftPosition - 40;


% reference phase
Ref_label = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'Select a reference phase', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'FontWeight', 'Bold', ...
    'HorizontalAlignment', 'left', ...
    'Position', [LeftPadding LeftPosition WIDTH/2 20]);

LeftPosition = LeftPosition - 75;

Ref_list = uicontrol(   'Parent', window, ...
    'Style', 'listbox', ...
    'String', CTString, ...
    'Enable', 'off', ...
    'Callback', @CT_change_Callback, ...
    'Position', [LeftPadding LeftPosition WIDTH/2 75]);

Ref_button = uicontrol(   'Parent', window, ...
    'Style', 'pushbutton', ...
    'String', 'All img', ...
    'Enable', 'off', ...
    'HorizontalAlignment', 'left', ...
    'Position', [(LeftPadding+WIDTH/2-65) LeftPosition 50 20], ...
    'Callback', @CT_button_Callback);

LeftPosition = LeftPosition - 40;

% registration
Registration_label = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'Registration', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'FontWeight', 'Bold', ...
    'HorizontalAlignment', 'left', ...
    'Position', [LeftPadding LeftPosition WIDTH/2 20]);


LeftPosition = LeftPosition - 50;

RegistrationGroup = uibuttongroup('Parent', window, ...
    'Units', 'Pixels', ...
    'BorderType', 'none', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'Position', [LeftPadding LeftPosition WIDTH/2 50]);

Registration_enable = uicontrol( 'Parent', RegistrationGroup, ...
    'Style', 'radiobutton', ...
    'String', 'Register 4D phases to reference', ...
    'Enable', 'off', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'Position', [10 25 WIDTH/2 20]);

Registration_disable = uicontrol( 'Parent', RegistrationGroup, ...
    'Style', 'radiobutton', ...
    'String', 'Load existing deformation fields', ...
    'Enable', 'off', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'Position', [10 5 WIDTH/2 20]);

LeftPosition = LeftPosition - 50;

%enable 4D accumulation
Accumulation_label = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'Accumulation', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'FontWeight', 'Bold', ...
    'HorizontalAlignment', 'left', ...
    'Position', [LeftPadding LeftPosition WIDTH/2 20]);
    
LeftPosition = LeftPosition - 30;

Enable_dose_accumulation =  uicontrol( 'Parent', window, ...
    'Style', 'checkbox', ...
    'String', 'Enable dose accumulation', ...
    'Value', AdvancedParam.DoseAccumulation, ...
    'Enable', 'off', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'HorizontalAlignment', 'left', ...
    'Position', [LeftPadding LeftPosition WIDTH/2 22]);
    
LeftPosition = LeftPosition - 60;


%%%%%%%%%%% Right pannel %%%%%%%%%%%%

% Robustness mode
Robust_label = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'Robustness test mode', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'FontWeight', 'Bold', ...
    'FontSize', 14, ...
    'HorizontalAlignment', 'left', ...
    'Position', [RightPadding RightPosition WIDTH/2 30]);

RightPosition = RightPosition - 85;

%enable robust mode
Robustness_test_Group = uibuttongroup('Parent', window, ...
    'Units', 'Pixels', ...
    'BorderType', 'none', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'SelectionChangedFcn', @Robust_mode_Callback, ...
    'Position', [RightPadding RightPosition WIDTH/2 75]);

robustness_disable = uicontrol( 'Parent', Robustness_test_Group, ...
    'Style', 'radiobutton', ...
    'String', 'Robustness test disabled', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'Position', [0 50 WIDTH*0.5 20]);

robustness_all_scenarios = uicontrol( 'Parent', Robustness_test_Group, ...
    'Style', 'radiobutton', ...
    'String', 'Simulate all combinations of uncertainty scenarios', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'Position', [0 25 WIDTH*0.5 20]);

robustness_random_sampling = uicontrol( 'Parent', Robustness_test_Group, ...
    'Style', 'radiobutton', ...
    'String', 'Randomly sample uncertainty scenarios', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'Position', [0 0 WIDTH*0.5 20]);


RightPosition = RightPosition - 45;

% setup errors
setup_label = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'Setup errors', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'FontWeight', 'Bold', ...
    'HorizontalAlignment', 'left', ...
    'Position', [RightPadding RightPosition WIDTH/2 20]);

setup_labelx = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'x', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'HorizontalAlignment', 'center', ...
    'Position', [RightPadding+100 RightPosition 50 20]);

setup_labely = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'y', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'HorizontalAlignment', 'center', ...
    'Position', [RightPadding+160 RightPosition 50 20]);

setup_labelz = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'z', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'HorizontalAlignment', 'center', ...
    'Position', [RightPadding+220 RightPosition 50 20]);

RightPosition = RightPosition - 25;

setup_systematic_label = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'Systematic:', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'HorizontalAlignment', 'left', ...
    'Position', [RightPadding RightPosition 75 20]);

setup_systematic_x = uicontrol( 'Parent', window, ...
    'Style', 'edit', ...
    'String', num2str(AdvancedParam.setup_systematic(1)), ...
    'HorizontalAlignment', 'center', ...
    'Position', [RightPadding+100 RightPosition 50 22]);

setup_systematic_y = uicontrol( 'Parent', window, ...
    'Style', 'edit', ...
    'String', num2str(AdvancedParam.setup_systematic(2)), ...
    'HorizontalAlignment', 'center', ...
    'Position', [RightPadding+160 RightPosition 50 22]);

setup_systematic_z = uicontrol( 'Parent', window, ...
    'Style', 'edit', ...
    'String', num2str(AdvancedParam.setup_systematic(3)), ...
    'HorizontalAlignment', 'center', ...
    'Position', [RightPadding+220 RightPosition 50 22]);

setup_systematic_units_label = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'mm', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'HorizontalAlignment', 'left', ...
    'Position', [RightPadding+280 RightPosition 100 20]);

RightPosition = RightPosition - 25;

setup_random_label = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'Random:', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'HorizontalAlignment', 'left', ...
    'Position', [RightPadding RightPosition 75 20]);

setup_random_x = uicontrol( 'Parent', window, ...
    'Style', 'edit', ...
    'String', num2str(AdvancedParam.setup_random(1)), ...
    'HorizontalAlignment', 'center', ...
    'Position', [RightPadding+100 RightPosition 50 22]);

setup_random_y = uicontrol( 'Parent', window, ...
    'Style', 'edit', ...
    'String', num2str(AdvancedParam.setup_random(2)), ...
    'HorizontalAlignment', 'center', ...
    'Position', [RightPadding+160 RightPosition 50 22]);

setup_random_z = uicontrol( 'Parent', window, ...
    'Style', 'edit', ...
    'String', num2str(AdvancedParam.setup_random(3)), ...
    'HorizontalAlignment', 'center', ...
    'Position', [RightPadding+220 RightPosition 50 22]);

setup_random_units_label = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'mm', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'HorizontalAlignment', 'left', ...
    'Position', [RightPadding+280 RightPosition 100 20]);

RightPosition = RightPosition - 40;


% range errors

range_label = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'Range uncertainties', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'FontWeight', 'Bold', ...
    'HorizontalAlignment', 'left', ...
    'Position', [RightPadding RightPosition WIDTH/2 20]);

RightPosition = RightPosition - 25;

range_systematic_label = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'Systematic:', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'HorizontalAlignment', 'left', ...
    'Position', [RightPadding RightPosition 75 20]);

range_systematic = uicontrol( 'Parent', window, ...
    'Style', 'edit', ...
    'String', num2str(AdvancedParam.range_systematic), ...
    'HorizontalAlignment', 'center', ...
    'Position', [RightPadding+100 RightPosition 50 22]);

range_systematic_units_label = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', '%', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'HorizontalAlignment', 'left', ...
    'Position', [RightPadding+160 RightPosition 100 20]);

RightPosition = RightPosition - 40;


% number of scenarios
NumScenarios_label = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'Number of scenarios', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'FontWeight', 'Bold', ...
    'HorizontalAlignment', 'left', ...
    'Position', [RightPadding RightPosition WIDTH/2 20]);

RightPosition = RightPosition - 25;

NumScenarios = uicontrol( 'Parent', window, ...
    'Style', 'edit', ...
    'String', num2str(AdvancedParam.NumScenarios), ...
    'Enable', 'off', ...
    'HorizontalAlignment', 'center', ...
    'Position', [RightPadding RightPosition 50 22]);

NumScenarios_label2 = uicontrol(  'Parent', window, ...
    'Style', 'text', ...
    'String', 'scenarios', ...
    'Enable', 'off', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'HorizontalAlignment', 'left', ...
    'Position', [RightPadding+75 RightPosition 100 20]);

RightPosition = RightPosition - 40;

% Select ROI
ROI_label = uicontrol( 'Parent', window, ...
    'Style', 'text', ...
    'String', 'ROI for robust analysis', ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'FontWeight', 'Bold', ...
    'HorizontalAlignment', 'left', ...
    'Position', [RightPadding RightPosition WIDTH/2 20]);

RightPosition = RightPosition - 150;

ROI_table = uitable(  window, ...
    'ColumnName', {'TV', 'OAR', 'Contour'}, ...
    'ColumnEditable', [true true false], ...
    'ColumnFormat', {'logical', 'logical', 'char'}, ...
    'RowName', [], ...
    'Data', ROIdata, ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'ColumnWidth', {30, 35, (WIDTH/2 - 68)}, ...
    'Position', [RightPadding RightPosition WIDTH/2 150]);

RightPosition = RightPosition - 60;

%%%%%%% Submit button %%%%%%%
Button = uicontrol(   'Parent', window, ...
    'Style', 'pushbutton', ...
    'String', 'Ok', ...
    'Position', [(WIDTH*0.6)-25 LeftPosition 50 20], ...
    'Callback', @OK_Button_Callback);


%%%%%%% set GUI initial states %%%%%%%

if(strcmp(AdvancedParam.CT_button, CT_button.String) ~= 1)
    CT_button_Callback();
end
CT_list.Value = AdvancedParam.CT_list;
Ref_list.Value = AdvancedParam.Ref_list;

if(AdvancedParam.register == 1)
    set(RegistrationGroup,'SelectedObject',Registration_enable);
else
    set(RegistrationGroup,'SelectedObject',Registration_disable);
end

mydata = {};
mydata.NewValue = {};
if(AdvancedParam.Robustness == 0)
    set(Robustness_test_Group,'SelectedObject',robustness_disable);
    mydata.NewValue.String = robustness_disable.String;
else
    if(AdvancedParam.ScenarioSampling == 0)
        set(Robustness_test_Group,'SelectedObject',robustness_all_scenarios);
        mydata.NewValue.String = robustness_all_scenarios.String;
    else
        set(Robustness_test_Group,'SelectedObject',robustness_random_sampling);
        mydata.NewValue.String = robustness_random_sampling.String;
    end
end
Robust_mode_Callback([], mydata);

if(AdvancedParam.Simu4D == 1)
    Enable_4D.Value = 1;
else
    Enable_4D.Value = 0;
end
Enable_4D_Callback();


%%%%%%% callback functions %%%%%%%

    function CT_change_Callback(source, data)
        check = Check_field_exist();
        if(check ~= 0)
            set(Registration_disable, 'Enable', 'on');
        else
            set(Registration_disable, 'Enable', 'off');
        end
    end


    function Enable_4D_Callback(source, data)
        AdvancedParam.Simu4D = (get(Enable_4D, 'Value') ~= 0);
        if(AdvancedParam.Simu4D == 1)
            set(CT_list, 'Enable', 'on');
            set(CT_button, 'Enable', 'on');
            set(Ref_list, 'Enable', 'on');
            set(Ref_button, 'Enable', 'on');
            set(Registration_enable, 'Enable', 'on');
            set(Enable_dose_accumulation, 'Enable', 'on');
            
            check = Check_field_exist();
            if(check ~= 0)
                set(Registration_disable, 'Enable', 'on');
            else
                set(Registration_disable, 'Enable', 'off');
            end
        else
            set(CT_list, 'Enable', 'off');
            set(CT_button, 'Enable', 'off');
            set(Ref_list, 'Enable', 'off');
            set(Ref_button, 'Enable', 'off');
            set(Registration_enable, 'Enable', 'off');
            set(Registration_disable, 'Enable', 'off');
            set(Enable_dose_accumulation, 'Enable', 'off');
        end
    end

    function CT_button_Callback(source, data)
        if(strcmp(CT_button.String, 'All img'))
            CT_list.Value = 1;
            CT_list.String = handles.images.name(2:end);
            CT_button.String = 'CT only';
            Ref_list.Value = 1;
            Ref_list.String = handles.images.name(2:end);
            Ref_button.String = 'CT only';
            AdvancedParam.CT_button = 'CT only';
        else
            CT_list.Value = 1;
            CT_list.String = CTString;
            CT_button.String = 'All img';
            Ref_list.Value = 1;
            Ref_list.String = CTString;
            Ref_button.String = 'All img';
            AdvancedParam.CT_button = 'All img';
        end
    end

    function Robust_mode_Callback(source, data)
        if( strcmp(data.NewValue.String, robustness_disable.String) == 1)
            AdvancedParam.Robustness = 0;
            set(setup_systematic_units_label, 'String', 'mm')
            set(setup_random_units_label, 'String', 'mm')
            set(range_systematic_units_label, 'String', '%')
            set(NumScenarios, 'String', '0')
            set(NumScenarios, 'Enable', 'off')
            set(NumScenarios_label2, 'Enable', 'off')
                
        else
            AdvancedParam.Robustness = 1;
            if( strcmp(data.NewValue.String, robustness_all_scenarios.String) == 1)
                AdvancedParam.ScenarioSampling = 0;
                set(setup_systematic_units_label, 'String', 'mm')
                set(setup_random_units_label, 'String', 'mm')
                set(range_systematic_units_label, 'String', '%')
                set(NumScenarios, 'String', '81')
                set(NumScenarios, 'Enable', 'off')
                set(NumScenarios_label2, 'Enable', 'off')
            else
                AdvancedParam.ScenarioSampling = 1;
                set(setup_systematic_units_label, 'String', 'mm (sigma)')
                set(setup_random_units_label, 'String', 'mm (sigma)')
                set(range_systematic_units_label, 'String', '% (sigma)')
                set(NumScenarios, 'String', '100')
                set(NumScenarios, 'Enable', 'on')
                set(NumScenarios_label2, 'Enable', 'on')
            end
        end
        
        
    end

    function OK_Button_Callback(source, data)
        if(strcmp(CT_button.String, 'CT only'))
            CTString = handles.images.name(2:end);
        end
        AdvancedParam.CT_phases = CTString(CT_list.Value);
        AdvancedParam.CT_list = CT_list.Value;
        AdvancedParam.reference = CTString{Ref_list.Value};
        AdvancedParam.Ref_list = Ref_list.Value;
        AdvancedParam.DoseAccumulation = (get(Enable_dose_accumulation, 'Value') ~= 0);
        
        if(strcmpi(get(get(RegistrationGroup,'SelectedObject'),'String'), 'Register 4D phases to reference') == 1)
            AdvancedParam.register = 1;
        else
            AdvancedParam.register = 0;
        end
        
        AdvancedParam.CT_button = CT_button.String;
        
        AdvancedParam.setup_systematic(1) = str2num(setup_systematic_x.String);
        AdvancedParam.setup_systematic(2) = str2num(setup_systematic_y.String);
        AdvancedParam.setup_systematic(3) = str2num(setup_systematic_z.String);
        AdvancedParam.setup_random(1) = str2num(setup_random_x.String);
        AdvancedParam.setup_random(2) = str2num(setup_random_y.String);
        AdvancedParam.setup_random(3) = str2num(setup_random_z.String);
        AdvancedParam.range_systematic = str2num(range_systematic.String);
        AdvancedParam.NumScenarios = str2num(NumScenarios.String);
        
        AdvancedParam.TV = {};
        AdvancedParam.OAR = {};
        ROIdata = ROI_table.Data;
        if(numel(ROIdata) > 0)
            for i=1:size(ROIdata,1)
                if(ROIdata{i,1} == 1)
                    AdvancedParam.TV{end+1} = ROIdata{i,3};
                end
                if(ROIdata{i,2} == 1)
                    AdvancedParam.OAR{end+1} = ROIdata{i,3};
                end
            end
        end
        
        close(window);
    end

%%%%%%%%%%%%%%%%%% other functions %%%%%%%%%%%%%%%%%%%%

    function res = Check_field_exist()
        res = 1;
        
        folder_path = fullfile(handles.dataPath, 'Reggui_registration_data');
        if(not(exist(folder_path,'dir')))
            res = 0;
            return;
        end
        
        for i = 1:length(CT_list.Value)
            file_name = [CTString{CT_list.Value(i)} '_to_' CTString{Ref_list.Value} '_log.dcm'];
            file_path = fullfile(folder_path, file_name);
            if(not(exist(file_path, 'file')))
                res = 0;
                return;
            end
        end
    end


    function res = check_contour_list(contour_name, list)
        tmp = [];
        for j=1:numel(list)
            tmp = [tmp strfind(lower(contour_name), lower(list{j}))];
        end
        
        if(isempty(tmp))
            res = false;
        else
            res = true;
        end
    end

uiwait(window)

end

