%% mydatenum
% Convert a text string representing a date (see function |datestr| for more information on format. For example, thestring could be generated by the function |dir|) into a serial date number by using the function |datenum|.
%
%% Syntax
% |res = mydatenum(datestring)|
%
%
%% Description
% |res = mydatenum(datestring)| convert the date string into a serial number
%
%
%% Input arguments
% |datestring| - _STRING_ -  Description of the date and time. Can be in English or French. 
%
%
%% Output arguments
%
% |res| - _SCALAR_ -  Serial number representing the date.
%
%
%% Contributors
% Authors : G.Janssens (open.reggui@gmail.com)

function res = mydatenum(datestring)
datevalue = double(datestring);
datevalue(datevalue>126)=101;
datestring = char(datevalue);
datestring = strrep(datestring,'fev','feb');
datestring = strrep(datestring,'avr','apr');
datestring = strrep(datestring,'mai','may');
datestring = strrep(datestring,'jui','jun');
ind = strfind(datestring,'-ao');
if(not(isempty(ind)))
    datestring(ind+3)='u';
end
datestring = strrep(datestring,'aou','aug');
datestring = strrep(datestring,'dec','dec');
res = datenum(datestring);
end
