function [myImage,myParams] = filters_list(Image_list,myTitle,param_list,default_params)

% Authors : G.Janssens

%% Use system background color for GUI components
panelColor = get(0,'DefaultUicontrolBackgroundColor');
myImage = [];
myParams = [];


%% ------------ Callback Functions ---------------

% Figure resize function
function figResize(src,evt)
    fpos = get(f,'Position');
    set(botPanel,'Position',...
        [1 1/20 fpos(3) fpos(4)*8/35])
    set(rightPanel,'Position',...
        [1 fpos(4)*8/35 fpos(3) fpos(4)*27/35])
end
    
% Bottom panel resize function
function botPanelResize(src, evt)
    bpos = get(botPanel,'Position');
    set(plotButton,'Position',...
        [bpos(3)*10/120 bpos(4)*2/8 bpos(3)*12/120 2])
    set(edit,'Position',...
        [bpos(3)*30/120 bpos(4)*2/8 bpos(3)*80/120 2])
    set(editLabel,'Position',...
        [bpos(3)*30/120 bpos(4)*4/8 bpos(3)*80/120 2])
end

% Right panel resize function
function rightPanelResize(src,evt)
    rpos = get(rightPanel,'Position');
    set(listBox,'Position',...
        [rpos(3)*4/32 rpos(4)*2/27 rpos(3)*24/32 rpos(4)*20/27]);
    set(listBoxLabel,'Position',...
        [rpos(3)*4/32 rpos(4)*24/27 rpos(3)*24/32 rpos(4)*2/27]);
end

%% Callback for list box
  function listBoxCallback(src,evt)
            
    end % listBoxCallback

%% Callback for edit

function editCallback(src,evt)

end

%% Callback for plot button
    function plotButtonCallback(src,evt)
        myImage = get(listBox,'String');
        myImage = myImage{get(listBox,'Value')};  
        myParams = get(edit,'String');
        delete(f);
        return
    end % plotButtonCallback
    

%% ------------ GUI layout ---------------

%% Set up the figure and defaults
f = figure('Units','characters',...
        'Position',[30 30 120 35],...
        'Color',panelColor,...
        'HandleVisibility','callback',...
        'IntegerHandle','off',...
        'Renderer','painters',...
        'Toolbar','figure',...
        'NumberTitle','off',...
        'Name','Image_list',...
        'Visible','off',...
        'ResizeFcn',@figResize);

%% Create the bottom uipanel
botPanel = uipanel('BorderType','etchedin',...
    'BackgroundColor',panelColor,...
    'Units','characters',...
    'Position',[1 1.5 120 8],...
    'Parent',f,...
    'ResizeFcn',@botPanelResize);

%% Create the right side panel
rightPanel = uipanel('bordertype','etchedin',...
    'BackgroundColor',panelColor,...
    'Units','characters',...
    'Position',[1 1 32 27],...
    'Parent',f,...
    'ResizeFcn',@rightPanelResize);

%% Add listbox and label
listBoxLabel = uicontrol(f,'Style','text','Units','characters',...
        'Position',[4 24 24 2],...
        'String',myTitle,...
        'FontSize',14,...
        'BackgroundColor',panelColor,...
        'Parent',rightPanel);
listBox = uicontrol(f,'Style','listbox','Units','characters',...
        'Position',[4 2 24 20],...
        'BackgroundColor','white',...
        'Max',10,'Min',1,...
        'String',Image_list,...
        'Parent',rightPanel,...
        'Callback',@listBoxCallback);

%% Add edit and label
editLabel = uicontrol(f,'Style','text','Units','characters',...
        'Position',[40 4 70 2],...
        'String',['Parameters = ',param_list],...
        'BackgroundColor',panelColor,...
        'Parent',botPanel);
edit = uicontrol(f,'Style','edit','Units','characters',...
        'Position',[40 2 70 2],...
        'BackgroundColor','white',...
        'String',default_params,...
        'Parent',botPanel,...
        'Callback',@editCallback);
    
%% Add buttons      
plotButton = uicontrol(f,'Style','pushbutton','Units','characters',...
        'Position',[10 2 15 2],...
        'String','OK',...
        'Parent',botPanel,...
        'Callback',@plotButtonCallback);
    
%% Initialize list box and make sure
% the hold toggle is set correctly
    listBoxCallback(listBox,[])       
    uiwait(f);
    
end % uipanel1




