function myString = image_edit(myTitle,myTags,myString)

% Authors : G.Janssens

%% Use system background color for GUI components
panelColor = get(0,'DefaultUicontrolBackgroundColor');


%% ------------ Callback Functions ---------------

% Figure resize function
    function figResize(src,evt)
        fpos = get(f,'Position');
        set(rightPanel,'Position',...
            [fpos(3)*1/150 fpos(4)*4/30 fpos(3)*148/150 fpos(4)*25/30])
        set(selectButton,'Position',...
            [fpos(3)*115/150 fpos(4)*1/30 fpos(3)*30/150 fpos(4)*2/30])
    end

% Right panel resize function
    function rightPanelResize(src,evt)
        rpos = get(rightPanel,'Position');
        set(listEdit,'Position',...
            [rpos(3)*50/140 rpos(4)*2/30 rpos(3)*88/140 rpos(4)*22/30]);
        set(Tags,'Position',...
            [rpos(3)*2/140 rpos(4)*2/30 rpos(3)*46/140 rpos(4)*22/30]);
        set(Title,'Position',...
            [rpos(3)*2/6 rpos(4)*26/30 rpos(3)*2/6 rpos(4)*2/30]);
    end

%% Callback for list box
    function listEditCallback(src,evt)
        guidata(src,gcf);       
    end % listEditCallback


%% Callback for select button
    function selectButtonCallback(src,evt)
        myString = get(listEdit,'String');
        delete(f);
        return
    end % selectButtonCallback


%% ------------ GUI layout ---------------

%% Set up the figure and defaults
f = figure('Units','characters',...
    'Position',[20 20 150 30],...
    'Color',panelColor,...
    'HandleVisibility','callback',...
    'IntegerHandle','off',...
    'Renderer','painters',...
    'Toolbar','figure',...
    'NumberTitle','off',...
    'Name','Image_list',...
    'Visible','off',...
    'ResizeFcn',@figResize);

%% Create the right side panel
rightPanel = uipanel('bordertype','etchedin',...
    'BackgroundColor',panelColor,...
    'Units','characters',...
    'Position',[5 1 140 25],...
    'Parent',f,...
    'ResizeFcn',@rightPanelResize);

%% Add listbox and label
Title = uicontrol(f,'Style','text','Units','characters',...
    'Position',[1 1 1 1],...
    'String',myTitle,...
    'FontSize',14,...
    'BackgroundColor',panelColor,...
    'Parent',rightPanel);
Tags = uicontrol(f,'Style','text','Units','characters',...
    'Position',[1 1 1 1],...
    'HorizontalAlignment','right',...
    'String',myTags,...
    'FontSize',10,...
    'BackgroundColor',panelColor,...
    'Parent',rightPanel);
listEdit = uicontrol(f,'Style','edit','Units','characters',...
    'Position',[1 1 1 1],...
    'HorizontalAlignment','left',...
    'String',myString,...
    'FontSize',10,...
    'BackgroundColor','white',...
    'Max',20,'Min',1,...
    'Parent',rightPanel,...
    'Callback',@listEditCallback);

%% Add buttons
selectButton = uicontrol(f,'Style','pushbutton','Units','characters',...
    'Position',[1 1 1 1],...
    'String','OK',...
    'Parent',f,...
    'Callback',@selectButtonCallback);

uiwait(f);

end % uipanel1




